name: Build & Push 🚀 | ScoutSuite ⎈

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone ScoutSuite official repository
        run: git clone https://github.com/nccgroup/ScoutSuite.git

      - name: Fetch the latest tag
        run: |
          cd ScoutSuite
          git fetch --tags
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./ScoutSuite/docker
          push: true
          file: ./ScoutSuite/docker/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/scoutsuite:${{ env.LATEST_TAG }}
