name: Build & Push 🚀 | ScoutSuite Official Image ⎈

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone ScoutSuite official repository
        run: git clone https://github.com/nccgroup/ScoutSuite.git

      - name: Fetch the latest tag
        run: |
          cd ScoutSuite
          git fetch --tags
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV

      - name: Get current tag version of Docker image
        run: |
          CURRENT_TAG=$(curl -s -H "Authorization: Bearer ${{ secrets.DOCKERHUB_TOKEN }}" "https://registry.hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/scoutsuite/tags?page_size=1" | jq -r '.results[0].name')
          echo "CURRENT_TAG=${CURRENT_TAG}" >> $GITHUB_ENV

      - name: Compare tags and decide whether to build
        run: |
          if [ "${{ env.LATEST_TAG }}" == "${{ env.CURRENT_TAG }}" ]; then
            echo "build=false" >> $GITHUB_ENV
          else
            echo "build=true" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: env.build == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./ScoutSuite/docker
          push: true
          file: ./ScoutSuite/docker/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/scoutsuite:${{ env.LATEST_TAG }}

      - name: No new version
        if: env.build == 'false'
        run: |
          echo "No new version found. Skipping the build process."
